# Generated by Django 5.2.5 on 2025-08-21 10:55

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Laptop",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("company", models.CharField(max_length=50)),
                ("ram", models.PositiveIntegerField(help_text="RAM size in GB")),
                ("storage", models.PositiveIntegerField(help_text="Storage in GB")),
                ("color", models.CharField(max_length=20)),
                ("stock", models.IntegerField()),
                ("price", models.IntegerField()),
            ],
        ),
    ]
