# Generated by Django 5.2.5 on 2025-09-02 10:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("laptop_app", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="laptop",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="image"),
        ),
    ]
