# Generated by Django 5.2.5 on 2025-09-07 11:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("laptop_app", "0002_laptop_image"),
    ]

    operations = [
        migrations.CreateModel(
            name="Testimonial",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("review", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
