# Generated by Django 5.2.5 on 2025-09-11 13:45

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("laptop_app", "0004_laptop_owner"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="laptop",
            name="owner",
        ),
    ]
